module.exports = {
  name: "Super User",
  userName: "superuser",
  password: "234",
  privillages: [
    "Customers",
    "Add New Customers",
    "View Transactions",
    "Update Customer",
    "Payment",
    "Dashboard",
    "Products",
    "Add New Products",
    "Delete Product",
    "Update Product",
    "Sales",
    "Employees",
    "Add New Employees",
    "Give User",
    "Delete Employee",
    "Update Employee",
    "Adminstration",
    "Users",
    "Access",
    "Reset User",
    "Delete User",
    "Company Info",
    "Setting",
  ],
};


// "@testing-library/jest-dom": "^5.11.4",
// "@testing-library/react": "^11.1.0",
// "@testing-library/user-event": "^12.1.10",