module.exports = {
  name: "Super User",
  userName: "superuser",
  password: "234",
  privillages: [
    "Customers",
    "Add New Customers",
    "View Transactions",
    "Update Customer",
    "Payment",
    "Dashboard",
    "Products",
    "Add New Products",
    "Delete Product",
    "Update Product",
    "Sales",
    "Employees",
    "Add New Employees",
    "Give User",
    "Delete Employee",
    "Update Employee",
    "Adminstration",
    "Users",
    "Access",
    "Reset User",
    "Delete User",
    "Company Info",
    "Setting",
    "New Order",
    "Sales Report",
    "View Sales",
    "Purchases",
    "New Purchase",
    "Purchase Report",
    "Reports",
    "Vendors",
    "Add New Vendors",
    "View Transactions",
    "Update Vendor",
    "View Purchases",
    "Payment",
    "Available",
    "Print",
    "Transactions",
    "Cancel Transaction",
    "Expenses",
    "Add New Expenses",
    "Update Expense",
    "Delete Expense",
    "MyCv",
    "Sales Summary",
    "Purchases Summary",
    "Purchases By Date",
    "Sales By Date",
    "Import Products",
    "Restore Transaction"
  ],
};


// "@testing-library/jest-dom": "^5.11.4",
// "@testing-library/react": "^11.1.0",
// "@testing-library/user-event": "^12.1.10",


// "@electron/remote": "^1.0.2",
    // "@emotion/react": "^11.7.1",
    // "@emotion/styled": "^11.6.0",

// "@mui/icons-material": "^5.8.4",
// "web-vitals": "^1.0.1"

// "react-scripts": "4.0.2",

 